//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionID { get; set; }
        public int userID { get; set; }
        public System.DateTime transactionDate { get; set; }
        public string transactionLocation { get; set; }
        public Nullable<decimal> transactionCredit { get; set; }
        public Nullable<decimal> transationDebit { get; set; }
    
        public virtual User User { get; set; }
    }
}
