//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class User
    {
        public int autoID { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "First name required")]
        public string firstname { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last name required")]
        public string lastname { get; set; }

        [DisplayName("Student ID")]
        [Required(ErrorMessage = "Student ID required")]
        public int idNumber { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string userPass { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Compare("userPass")]
        public string confirmPass { get; set; }

        public bool admin { get; set; }
    }
}
