//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userId { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email_ID { get; set; }
        public string user_pass { get; set; }
        public bool admin { get; set; }
        public bool verify_email { get; set; }
        public System.Guid activation_code { get; set; }
    }
}
